SELECT CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR
 WHERE 1=1
   AND CAR_TYPE = '세단'
   AND CAR_ID IN (
    SELECT DISTINCT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE TO_CHAR(START_DATE,'MM') = '10'
 )
 ORDER BY 1 DESC